# Generated by Django 4.0.6 on 2022-07-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
