# Generated by Django 4.0.6 on 2022-07-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
